### ISSUE TITLE
"_yt.www" is not defined

### ISSUE THREAD

**Issue by Darkgrouptw** [chylex/Userscripts#1]
Hi, I find out that "_yt_www" is not defined in ActivityCheckRemoval.user.js. 
(Maybe youtube updated the code ?)
And I try to fix the code. I think it change the variable name to " _yt_player".
But I can't figure out which function _yt_player should called.

I capture my question.
![Question](https://i.imgur.com/o19rrm4.png)

**Comment by chylex** [comment]
Yea it's been broken for a while, I don't run into the activity check myself so I don't notice when it breaks, but I had a few people report it. Idk when I'll fix it.

**Comment by Darkgrouptw** [comment]
Can u give some tips about how did u find it?
Or which javascript I need to look into?
Or which keyword I can find?

Maybe, I can help to fix it by pull requests.
![](https://i.imgur.com/g68PcCk.png)

**Comment by chylex** [comment]
I found it by searching through the main javascript file and reverse-engineering how the activity check is triggered. I don't know what's changed and I don't think `_yt_player` is the correct thing to look in...

If I check my YT page which still has the old layout, `_yt_www` exists, so it's safe to assume YT is serving two completely different versions of the website and the script would need to be fixed for both.

**Comment by chylex** [comment]
Closing this issue as not planned, sorry. Personally I just never run into the activity check on YouTube, I don't know if it even exists anymore. If it does and someone else can fix it, I can accept a PR.
